---
- name: Install packages
  pacman: name={{ packages }} state=present update_cache=yes
  become: yes
  become_method: sudo

- name: Stow dotfiles
  command: stow {{ item }}  
  with_items: 
    - "{{ stow_packages }}"
